name: Main Branch Trigger

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main_branch_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install dependencies
        run: pnpm install

      - name: Build step
        run: pnpm build